### ISSUE TITLE
service-proxy war NamespaceHandler.java:[44] NamespaceHandlerAutoGenerated cannot be resolved

### ISSUE THREAD

**Issue by yzhang226** [membrane/service-proxy#258]
### i compile service-proxy in my local, occure following issue:
1. keytools package can not be found, fix this by replace maven-compiler-plugin's compilerId to eclipse
2. core's NamespaceHandlerAutoGenerated missed, fix this by add annotationProcessor in parent-pom
### 3. war's NamespaceHandlerAutoGenerated cannot be resolved, 
    i try repeat second to regenerate this java file, it failed.
#### i already read NamespaceHandler.java's comment, 		 

* When using Maven, it should work automatically. Make sure that
		 * * either you are building *all* service-proxy modules at once (invoking
		 *   "mvn" in service-proxy's main directory).
		 * * or you have installed the service-proxy-annot module locally (run
		 *   "mvn install" in service-proxy/annot once since the last version bump
		 *   before compiling service-proxy/core).

**but core is done, failed with build war.**

can some help me?

**Comment by rrayst** [comment]
The problem was caused by unused imports of sun.security.* packages. I just pushed a fix to master.

The project should now build without any changes. (It does so within our Docker test container,  which is based on the Dockerfile in the project root.)

Thanks for pointing it out!

**Comment by yzhang226** [comment]
after i pull latest code, execute mvn compile install -Dmaven.test.skip=true, 
still get the same error, as following:
```
[INFO] service-proxy-parent ............................... SUCCESS [  0.618 s]
[INFO] service-proxy-annot ................................ SUCCESS [  2.091 s]
[INFO] service-proxy-test ................................. SUCCESS [  0.888 s]
[INFO] service-proxy-core ................................. SUCCESS [  6.649 s]
[INFO] membrane-service-proxy ............................. SUCCESS [  5.316 s]
[INFO] service-proxy-osgi ................................. SUCCESS [ 55.265 s]
[INFO] service-proxy-osgi-extender ........................ SUCCESS [  3.607 s]
[INFO] service-proxy-war .................................. FAILURE [  0.359 s]
[INFO] service-proxy-sar .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:15 min
[INFO] Finished at: 2016-06-06T09:51:08+08:00
[INFO] Final Memory: 62M/1495M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project service-proxy-war: Compilation failure
[ERROR] /storage/git_repo/service-proxy/war/src/main/java/com/predic8/membrane/servlet/config/spring/NamespaceHandler.java:[44,2] error: can not find symbol
```

then , i check the direcoty `war/target/generated-sources/annotations`, 
* there are not generated java file  at all. *

how can i fix this?
